# Generated by Django 5.1.4 on 2026-02-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-created_at'], 'verbose_name': 'tablero', 'verbose_name_plural': 'tableros'},
        ),
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['order'], 'verbose_name': 'columna', 'verbose_name_plural': 'columnas'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order'], 'verbose_name': 'tarea', 'verbose_name_plural': 'tareas'},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['-created_at'], 'verbose_name': 'espacio de trabajo', 'verbose_name_plural': 'espacios de trabajo'},
        ),
        migrations.AddField(
            model_name='task',
            name='assignee_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='persona asignada'),
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de finalización'),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje de avance (0-100)', verbose_name='progreso'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de inicio'),
        ),
    ]
