# Generated by Django 5.1.4 on 2026-02-18 01:30

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_board_options_alter_column_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('delayed', 'Retrasado'), ('completed', 'Completado'), ('custom', 'Personalizado')], default='custom', help_text='Estado semántico para lógica de negocio (auto-fechas, progreso).', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee_name',
            field=models.CharField(blank=True, default='', help_text='Nombre libre para asignar a personas sin cuenta en el sistema.', max_length=255, verbose_name='persona asignada (externa)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje de avance (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='progreso'),
        ),
        migrations.AddIndex(
            model_name='column',
            index=models.Index(fields=['board', 'order'], name='columns_board_i_5c985a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['column', 'order'], name='tasks_column__79f635_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='tasks_priorit_a9efa1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee'], name='tasks_assigne_462a05_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('progress__lte', 100)), name='progress_max_100'),
        ),
    ]
