# Generated by Django 5.1.4 on 2026-02-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_column_status_alter_task_assignee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='color',
            field=models.CharField(default='#6B7280', help_text='Color hexadecimal para el encabezado del grupo (ej: #3B82F6).', max_length=7),
        ),
    ]
