# Generated by Django 5.1.4 on 2026-02-23 06:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_taskcomment_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('assigned', 'Asignada'), ('group_assigned', 'Asignada a grupo'), ('moved', 'Movida'), ('comment', 'Comentario'), ('completed', 'Completada')], max_length=20),
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('individual_progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='progreso individual')),
                ('user_color', models.CharField(default='#0073ea', help_text='Color asignado al usuario para esta tarea (hex).', max_length=7)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asignación de tarea',
                'verbose_name_plural': 'asignaciones de tareas',
                'db_table': 'task_assignments',
                'unique_together': {('task', 'user')},
            },
        ),
    ]
