# Generated by Django 5.1.4 on 2026-02-23 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_notification_type_taskassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(blank=True, help_text='Tareas que deben completarse antes que esta', related_name='dependent_tasks', to='projects.task', verbose_name='dependencias'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Permite crear jerarquías (Grupos/Hitos)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='projects.task', verbose_name='tarea padre'),
        ),
    ]
