# Generated by Django 5.1.4 on 2026-02-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('gestor', 'Gestor'), ('desarrollador', 'Desarrollador'), ('observador', 'Observador')], default='desarrollador', max_length=20, verbose_name='rol'),
        ),
    ]
