# Generated by Django 5.1.4 on 2026-02-28 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL del avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Google ID'),
        ),
        migrations.CreateModel(
            name='AllowedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='correo')),
                ('domain', models.CharField(blank=True, help_text='ej: stwards.com — permite todos los emails de ese dominio', max_length=255, null=True, verbose_name='dominio')),
                ('role', models.CharField(choices=[('administrador', 'Administrador'), ('gestor', 'Gestor'), ('desarrollador', 'Desarrollador'), ('observador', 'Observador')], default='desarrollador', max_length=20, verbose_name='rol asignado')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='usado el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='invitado por')),
            ],
            options={
                'verbose_name': 'email permitido',
                'verbose_name_plural': 'emails permitidos',
                'db_table': 'allowed_emails',
                'constraints': [models.CheckConstraint(condition=models.Q(('email__isnull', False), ('domain__isnull', False), _connector='OR'), name='allowedemail_email_or_domain_required')],
            },
        ),
    ]
