# Generated by Django 5.1.4 on 2026-03-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_avatar_url_user_google_id_allowedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedemail',
            name='name',
            field=models.CharField(blank=True, help_text='Nombre del usuario (opcional). Se usa como nombre visible al hacer su primer login con Google.', max_length=255, null=True, verbose_name='nombre'),
        ),
    ]
